### ISSUE TITLE
[Feature request] Setup using existing workspace

### ISSUE THREAD

**Issue by lrockreal** [ArvidSilverlock/Pilot.lua-Luau-LSP#5]
Use `lune run pilot setup <path>` to generate `types/` and `.vscode/` under `<path>` instead of under `./workspace`. Default path can remain as `./workspace` for backwards compatibility

Additional request: Custom output location for `types/` folder?

**Comment by ArvidSilverlock** [comment]
Added `lune run pilot -o <path> --types=<types subdirectory>`.

Note that issues occur if you generate into the same directory with a different types folder.

As of right now it will likely not work if you specify the types to be output in the same directory as the output rather than specifying a subdirectory.
